language: c

env:
 - FILE_URL=git://github.com/file/file.git FILE_TESTS_URL=git://github.com/hanzz/file-trunk-tests.git

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq automake libtool make python zlib1g-dev

script:
 - git clone --depth=1 $FILE_URL file
 - cd file
 - git log -1
 - autoreconf -f -i
 - ./configure --disable-silent-rules
 - make -j4
 - make -C tests check
 - sudo make install
 - cd ..
 - which file
 - file --version

 - git clone --depth=1 $FILE_TESTS_URL file-tests
 - cd file-tests/file-tests
 - python update-db.py file file/magic/Magdir
 - python fast-regression-test.py
