language: c

os:
 - linux
 - osx

env:
 global:
  - FILE_URL=git://github.com/file/file.git

before_install:
 - env
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq automake libtool make python zlib1g-dev; fi
 # workaround for /usr/local/Library/ENV/4.3/sed: No such file or directory
 # http://stackoverflow.com/a/38471887
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew reinstall -s libtool; fi

script:
 # abort on any command failure
 - set -e
 - git clone --depth=100 $FILE_URL file
 - cd file
 - test -z "$commit" || git checkout $commit
 - git log -1
 - autoreconf -f -i
 - ./configure --disable-silent-rules --prefix=/usr
 - make -j4
 - make -C tests check
 - sudo make install
 - cd ..
 - which file
 - file --version

 - python update-db.py -m file/magic/Magdir
 - python fast-regression-test.py

# vim:ts=1:sw=1:et
